### ISSUE TITLE
Error Could not load file or assembly 'Newtonsoft.Json when compiling

### ISSUE THREAD

**Issue by CtrlShiftEscape** [Liminiens/json-provider#14]
`Main.fs(38,20,38,49): typecheck error FS3033: The type provider 'JsonProviderImplementation+JsonProvider' reported an error: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)`
I have Newtonsoft.Json reference in my project

**Comment by Liminiens** [comment]
Hi! Can you please send a repro? It seems to work fine for me in old fsproj/new fsproj projects.
